### ISSUE TITLE
"Show sample projects" button doesn't work

### ISSUE THREAD

**Issue by jammily** [sugarlabs/physics#32]
"Show sample projects" button doesn’t show up the sample projects.

**Comment by quozl** [comment]
Works for me.

![physics-samples](https://user-images.githubusercontent.com/2936481/29857812-dbee0ada-8d9d-11e7-9922-86878c0b8517.png)

If after testing again it still doesn't work, please re-open with more detail;
* version of Physics, including git hash,
* version of Sugar,
* activity log.

**Comment by jammily** [comment]
Last commit in master branch: 607de7322cf579b417d7ccc7638c0b3ff6b6de01
Sugar version 0.110
There's no error in the activity log.

**Comment by quozl** [comment]
You didn't say it was on Fedora 18.  Please mention operating system version in future.

Please try with 1469c0b and let me know what you think.

**Comment by jammily** [comment]
Great!! I can see the samples. Thank you!!

**Comment by srevinsaju** [comment]
@quozl I am running into the same issue on python2 and python3
