### ISSUE TITLE
Shapes, especially those linked by chain, cannot be moved

### ISSUE THREAD

**Issue by PaulMacDonald** [sugarlabs/physics#34]
PROBLEM: When using the Physics activity in SOAS, when two shapes are linked with a chain by the user, there is an odd occurrence where no shapes (whether they are chain-linked or not) can be moved at all by the drag tool. The chain can be moved, but all shapes are rendered immovable except by another falling shape that has been created. (Which will also be immovable once it hits the ground.)

SUGGESTED REMEDY: The reason for this problem would possibly be found in the code that allows for shapes chained together to be moved together (i.e. -- when one is dragged around, the other is dragged behind it), as it affects the motion of multiple shapes on the screen, and for some reason could possibly be affecting the mobility of all shapes in the activity once any two or more shapes are chained together. Addressing this specific segment of code, and perhaps limiting its scope of what shapes it can affect (or, rather, how easily it is allowed access to their mobility or immobility) might fix this issue.

**Comment by quozl** [comment]
Thanks.  Please point at the source code line you think is the problem?

**Comment by PaulMacDonald** [comment]
Unsure -- Which file would I look in to find the code that handles and creates chains that link shapes?

**Comment by quozl** [comment]
Oh, okay.  I was wondering how speculative your suggested remedy was.  I don't know either; finding the file will form part of the remediation.

**Comment by sparshg** [comment]
So I created a few circles, and linked two of them with chains. I clicked on the Grab tool and everything seems draggable. Is this issue still there?

**Comment by chimosky** [comment]
Tested on F38 SOAS and it works just fine, issue doesn't exist anymore.
