### ISSUE TITLE
Physics JS Activity Exiting/Re-entering Bug

### ISSUE THREAD

**Issue by PaulMacDonald** [sugarlabs/physics#35]
PROBLEM: When using the Physics activity in SOAS, after exiting and re-entering at least once (sometimes twice), the activity’s screen goes entirely black, no matter how many times the activity is restarted. Once this has occurred, the only way to undo it is to reboot the computer and Sugar.
	Also, sometimes, when exiting the activity, the cursor visually freezes. The cursor itself can still be moved and used, but the movement is not visible.

SUGGESTED REMEDY: These problems could possibly be coming from the segment of the program that saves progress in an activity after it has been exited.

**Comment by quozl** [comment]
Works for me.  Not enough information.  What version of SoaS?  What version of Physics?  What does the Log activity say about the events associated with the problem?  Are you sure you are using a JS implementation of Physics?  (You have JS in your issue title; but this repository is a Python implementation, so it is important to check.)

**Comment by PaulMacDonald** [comment]
I am using the latest website release of SOAS, which was released on November 19, 2017. Downloaded straight from sugarlabs.org.

**Comment by quozl** [comment]
Thanks.  When I get a moment, I'll test again, but my guess is that you've got an old version of Physics or you've hit a snag with Fedora that SoaS faithfully renders.  You can help by giving more detail as above.

**Comment by quozl** [comment]
I've tested with `Fedora-SoaS-Live-x86_64-27-1.6.iso` which has Physics-32.1 by starting and stopping the activity many times, and the issue does not occur.  We'll certainly need more details and a method to reproduce.  Please re-open once these details are available.
