### ISSUE TITLE
Physics JS Activity "Forever Falling" Bug

### ISSUE THREAD

**Issue by PaulMacDonald** [sugarlabs/physics#36]
PROBLEM: A circle larger than the capacity of the screen was created, and then thrown (using the drag tool) at an exceptionally accelerated rate into the air, and off to the side. It then proceeded to (after a minute or two of playing with other shapes) reappear on the screen by suddenly falling straight down from the top, and falling through the bottom of the screen. It then continued to do so, each time moving ever so slightly to the right each time.

SUGGESTED REMEDY: Once a shape’s position has passed below the bottom of the screen, its downward momentum should be set to zero, and its position set as being on the ground, so that it cannot pass below the bottom border of the screen. In addition, once a shape has passed beyond the left or right boundaries of the screen, it should be deleted.

**Comment by quozl** [comment]
Thanks, interesting.

**Comment by quozl** [comment]
Tested, does not reproduce.  Please re-open when this issue can be reliably reproduced.
