### ISSUE TITLE
Object colour selector rendered incorrectly

### ISSUE THREAD

**Issue by quozl** [sugarlabs/physics#41]
* [ ] toolbar button is not the same size as the other buttons,
* [ ] colour swatches are too small to be usable,

![Screenshot_test_2019-04-06_13:45:15](https://user-images.githubusercontent.com/2936481/55663978-71300800-5872-11e9-9f6c-49b007b5180b.png)

Seen on Ubuntu 18.04 with Physics-34.

**Comment by Hrishi1999** [comment]
Cannot reproduce. But the color toolbar button is smaller when compared to other buttons. 
![phy](https://user-images.githubusercontent.com/16208722/55668752-9e3ce480-588b-11e9-8170-4376bd726f6a.PNG)
(Ubuntu 18.04 / Physics 34)

**Comment by Aniket21mathur** [comment]
@Hrishi1999  agreed. Tested on Ubuntu 18.10 with Physics 34.

**Comment by quozl** [comment]
Okay, thanks.  That suggests regression from Sugar 0.112 to 0.113.  Can you both confirm you were testing with 0.112?  0.113 is the latest release.

**Comment by Hrishi1999** [comment]
Yes, I am using Sugar 0.112.

**Comment by nswarup14** [comment]
Testing with Sugar v0.114
![Screenshot from 2019-08-09 10-24-38](https://user-images.githubusercontent.com/34597895/62819817-1851e280-bb78-11e9-9840-3700e289ad69.png)

I am facing the same issue as @quozl

**Comment by srevinsaju** [comment]
I guess this issue may be closed 
@quozl @chimosky

**Comment by quozl** [comment]
Thanks!  Missing linked issues; e.g. "Fixes #41".
